//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientIntegrationApp.IntegrationServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WcfIntegrationServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneResidencialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCelular {
            get {
                return this.NumeroCelularField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCelularField, value) != true)) {
                    this.NumeroCelularField = value;
                    this.RaisePropertyChanged("NumeroCelular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneResidencial {
            get {
                return this.TelefoneResidencialField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneResidencialField, value) != true)) {
                    this.TelefoneResidencialField = value;
                    this.RaisePropertyChanged("TelefoneResidencial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IntegrationServiceReference.IIntegration")]
    public interface IIntegration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegration/buscarCliente", ReplyAction="http://tempuri.org/IIntegration/buscarClienteResponse")]
        ClientIntegrationApp.IntegrationServiceReference.Cliente buscarCliente(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegration/atualizarCliente", ReplyAction="http://tempuri.org/IIntegration/atualizarClienteResponse")]
        int atualizarCliente(string nome, System.DateTime dataNascimento, string numeroCelular);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegration/retornaClientes", ReplyAction="http://tempuri.org/IIntegration/retornaClientesResponse")]
        ClientIntegrationApp.IntegrationServiceReference.Cliente[] retornaClientes();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntegrationChannel : ClientIntegrationApp.IntegrationServiceReference.IIntegration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegrationClient : System.ServiceModel.ClientBase<ClientIntegrationApp.IntegrationServiceReference.IIntegration>, ClientIntegrationApp.IntegrationServiceReference.IIntegration {
        
        public IntegrationClient() {
        }
        
        public IntegrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientIntegrationApp.IntegrationServiceReference.Cliente buscarCliente(string nome) {
            return base.Channel.buscarCliente(nome);
        }
        
        public int atualizarCliente(string nome, System.DateTime dataNascimento, string numeroCelular) {
            return base.Channel.atualizarCliente(nome, dataNascimento, numeroCelular);
        }
        
        public ClientIntegrationApp.IntegrationServiceReference.Cliente[] retornaClientes() {
            return base.Channel.retornaClientes();
        }
    }
}
